# Generated by Django 5.2.7 on 2025-10-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro", "0005_colaborador"),
    ]

    operations = [
        migrations.CreateModel(
            name="AberturaOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_os",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("descricao_os", models.TextField()),
                ("ssm", models.CharField(max_length=10)),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.centrocusto",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.cliente",
                    ),
                ),
                (
                    "motivo_intervencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro.intervencao",
                    ),
                ),
            ],
        ),
    ]
