# Generated by Django 5.2.7 on 2025-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancamento", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aberturaos",
            name="situacao",
            field=models.CharField(
                choices=[("AB", "Em Aberto"), ("FI", "Finalizado")],
                default="AB",
                max_length=2,
                verbose_name="Situação da OS",
            ),
        ),
    ]
