# Generated by Django 5.2.7 on 2025-11-13 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0005_colaborador"),
        ("lancamento", "0002_aberturaos_situacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApontamentoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos",
                        to="cadastro.colaborador",
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos",
                        to="lancamento.aberturaos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento de Horas",
                "verbose_name_plural": "Apontamentos de Horas",
                "ordering": ["-data_inicio"],
            },
        ),
    ]
