# Generated by Django 5.2.7 on 2025-11-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancamento", "0003_apontamentohoras"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamentohoras",
            name="tipo_dia",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
