# Generated by Django 5.2.7 on 2026-01-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_cliente_id_alter_cliente_cod_cliente"),
        ("lancamento", "0004_apontamentohoras_tipo_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aberturaos",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastro.cliente",
            ),
        ),
    ]
