# Generated by Django 5.2.7 on 2026-01-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_cliente_id_alter_cliente_cod_cliente"),
        ("lancamento", "0005_alter_aberturaos_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aberturaos",
            name="motivo_intervencao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aberturaos",
                to="cadastro.intervencao",
            ),
        ),
    ]
