# Generated by Django 5.2.7 on 2026-01-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancamento", "0006_alter_aberturaos_motivo_intervencao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservacaoOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "os",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="lancamento.aberturaos",
                    ),
                ),
            ],
        ),
    ]
