# Generated by Django 5.2.7 on 2026-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancamento", "0007_observacaoos"),
    ]

    operations = [
        migrations.AddField(
            model_name="aberturaos",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ObservacaoOS",
        ),
    ]
