# Generated by Django 5.2.7 on 2025-10-09 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centrocusto",
            name="tag",
        ),
        migrations.AddField(
            model_name="centrocusto",
            name="centro_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcentros",
                to="cadastro.centrocusto",
            ),
        ),
        migrations.AlterField(
            model_name="centrocusto",
            name="cod_centro",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
