# Generated by Django 5.2.7 on 2025-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_remove_centrocusto_tag_centrocusto_centro_pai_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cod_cliente", models.IntegerField(primary_key=True, serialize=False)),
                ("nome_cliente", models.CharField(max_length=100)),
            ],
        ),
    ]
