# Generated by Django 5.2.7 on 2025-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervencao",
            fields=[
                (
                    "cod_intervencao",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
        ),
    ]
