# Generated by Django 5.2.7 on 2025-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0005_colaborador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="matricula",
            field=models.CharField(
                max_length=4, unique=True, verbose_name="Número da Matrícula"
            ),
        ),
    ]
