# Generated by Django 5.2.7 on 2025-11-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_alter_colaborador_matricula"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cod_cliente",
            field=models.IntegerField(unique=True),
        ),
    ]
