# Generated by Django 5.2.7 on 2026-01-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AberturaOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_os", models.CharField(max_length=8, unique=True)),
                ("descricao_os", models.TextField()),
                (
                    "situacao",
                    models.CharField(
                        choices=[("ABERTA", "Aberta"), ("FINALIZADA", "Finalizada")],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservacaoOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacao", models.TextField()),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "os",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="relatorios.aberturaos",
                    ),
                ),
            ],
        ),
    ]
