# Generated by Django 5.2.7 on 2026-01-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observacaoos",
            name="os",
        ),
        migrations.DeleteModel(
            name="AberturaOS",
        ),
        migrations.DeleteModel(
            name="ObservacaoOS",
        ),
    ]
